/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author paupi
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btMorador = new javax.swing.JMenuItem();
        btVisitante = new javax.swing.JMenuItem();
        btFuncionario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btEncomenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetofinalvai/Imagens/condominioresized.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 340));

        jMenu1.setText("Cadastro");

        btMorador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetofinalvai/Imagens/Icones/icone morador24.png"))); // NOI18N
        btMorador.setText("Morador");
        btMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMoradorActionPerformed(evt);
            }
        });
        jMenu1.add(btMorador);

        btVisitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetofinalvai/Imagens/Icones/visitante24.png"))); // NOI18N
        btVisitante.setText("Visitante");
        btVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisitanteActionPerformed(evt);
            }
        });
        jMenu1.add(btVisitante);

        btFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetofinalvai/Imagens/Icones/guia-turistico24.png"))); // NOI18N
        btFuncionario.setText("Funcionário");
        btFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(btFuncionario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Encomenda");

        btEncomenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetofinalvai/Imagens/Icones/estoque-pronto24.png"))); // NOI18N
        btEncomenda.setText("Encomenda");
        btEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEncomendaActionPerformed(evt);
            }
        });
        jMenu2.add(btEncomenda);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMoradorActionPerformed
        
        telaMoradores t1 = new telaMoradores();
        t1.setVisible(true);
    }//GEN-LAST:event_btMoradorActionPerformed

    private void btVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisitanteActionPerformed
        // TODO add your handling code here:
        telaVisitante t4 = new telaVisitante();
        t4.setVisible(true);
    }//GEN-LAST:event_btVisitanteActionPerformed

    private void btFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncionarioActionPerformed
        // TODO add your handling code here:
        TelaFunc t3 = new TelaFunc();
        t3.setVisible(true);
    }//GEN-LAST:event_btFuncionarioActionPerformed

    private void btEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEncomendaActionPerformed
        // TODO add your handling code here:
        TelaEncomenda t2 = new TelaEncomenda();
        t2.setVisible(true);
        
    }//GEN-LAST:event_btEncomendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btEncomenda;
    private javax.swing.JMenuItem btFuncionario;
    private javax.swing.JMenuItem btMorador;
    private javax.swing.JMenuItem btVisitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
